Fix issue labeling double message
mattermost/mattermost-plugin-github pull request #393
Opened 2020-10-17 17:41 UTC by EnzoBtv

#### Summary
This PR fixed double messaging when an issue gets labeled in the process of creating it

#### Ticket Link
This PR is linked with the issue #389

2020-10-17 17:41 UTC, mattermod commented
Hello @EnzoBtv,

Thanks for your pull request! A Core Committer will review your pull request soon. For code contributions, you can learn more about the review process [here](https://developers.mattermost.com/contribute/getting-started/code-review/).

2020-10-21 10:04 UTC, hanzei requested changes
Thanks for the contribution! A few comments below

2020-10-21 10:04 UTC, hanzei commented on server/plugin/webhook.go
> +	if time.Now().Unix()-issue.GetCreatedAt().Unix() <= 3 && action == "labeled" {
Could you please add a comment explaining why this is done?

2020-10-21 10:04 UTC, hanzei commented on server/plugin/webhook.go
> +	if time.Now().Unix()-issue.GetCreatedAt().Unix() <= 3 && action == "labeled" {
Nit pick: Does it make sense to reverse the order of the checks as `action == "labeled"` is more likely to be false?

2020-10-21 10:04 UTC, hanzei commented on server/plugin/webhook.go
> +	if time.Now().Unix()-issue.GetCreatedAt().Unix() <= 3 && action == "labeled" {
Instead of relying on the hard to remember semantic of `Unix()` should [`Sub`](https://pkg.go.dev/time#Time.Sub) get used instead?

2020-10-21 16:08 UTC, EnzoBtv commented
I've done the requested changes

2020-10-21 18:25 UTC, hanzei approved these changes
LGTM :+1:

2020-10-21 18:34 UTC, mickmister approved these changes
Awesome! LGTM :+1:

2020-10-25 21:35 UTC, DHaussermann approved these changes
Tested and passed
- The creation of the issue now sends only one event when the label is include
- Brief regression testing found no issues
LGTM!

Thanks @EnzoBtv . This is a great enhancement that really improves the the expirience!

2020-10-26 23:17 UTC, mattermod commented
Will try to auto merge this PR once all tests and checks are passing. This might take up to an hour.

2020-10-26 23:17 UTC, jasonblais commented
cc @mickmister @hanzei please help with merging if `Automerge` label is unsuccessful.

2020-10-26 23:24 UTC, mattermod commented
Trying to auto merge this PR.

2020-10-26 23:24 UTC, merged

2020-10-26 23:24 UTC, mattermod commented
Pull Request successfully merged
SHA: ee9cba65ffaba909e83784f9f66078dced7bf29b