Revert "GitHub LHS icon will not show on 1st login until the browser is refreshed"
mattermost/mattermost-plugin-github pull request #539
Opened 2022-02-22 05:29 UTC by maisnamrajusingh

Reverts mattermost/mattermost-plugin-github#515

2022-02-22 05:29 UTC, mattermod commented
Hello @maisnamrajusingh,

Thanks for your pull request! A Core Committer will review your pull request soon. For code contributions, you can learn more about the review process [here](https://developers.mattermost.com/contribute/getting-started/code-review/).

2022-02-22 05:29 UTC, maisnamrajusingh commented
@hanzei  I am reverting the PR for now and prioritizing on  fixing this on my end.

2022-02-22 13:52 UTC, hanzei requested changes
Let's see if https://github.com/mattermost/mattermost-plugin-github/pull/540 gets approved soon

2022-03-01 11:14 UTC, hanzei commented
Closing as https://github.com/mattermost/mattermost-plugin-github/pull/540 is merged

2022-03-01 11:14 UTC, closed without merging