Make playwright tests run off of ci workflow run
mattermost/mattermost-plugin-github pull request #681
Opened 2023-06-05 01:34 UTC by mickmister

#### Summary

Playwright tests are currently failing for fork PRs. This PR solves this by running the workflow alongside the `ci` workflow, to access variables for the Mattermost project during the workflow run.

Context https://community.mattermost.com/core/pl/buyo3qkq8tdm9yeobg6dsih4gy

#### Ticket Link

Fixes https://mattermost.atlassian.net/browse/MM-53014

2023-06-05 06:56 UTC, hanzei requested changes
I don't see any playwright runs for this PR. Should they run for this PR?

2023-06-05 23:27 UTC, mickmister commented
@hanzei It could be because the `ci / plugin-ci / delivery (pull_request)` job was skipped. It's possible all of the jobs in that workflow need to run/complete?

2023-06-06 07:44 UTC, toninis approved these changes
👍🏼

2023-06-06 07:44 UTC, toninis commented
> @hanzei It could be because the `ci / plugin-ci / delivery (pull_request)` job was skipped. It's possible all of the jobs in that workflow need to run/complete?

This step only runs on master or main @mickmister https://github.com/mattermost/actions-workflows/blob/main/.github/workflows/plugin-ci.yml#L78

2023-06-20 08:41 UTC, hanzei approved these changes

2023-06-20 08:42 UTC, merged