[GH-693] Fix improper rendering of some unreads in the response of "/github todo" command
mattermost/mattermost-plugin-github pull request #699
Opened 2023-09-26 08:42 UTC by raghavaggarwal2308

#### Summary
The URL that was used to create the pretext of the unread message and the repo URL was missing in the body of Discussion and CheckSuite type unread. We updated the code to use the repo link present in the body of an unread message. Also, we couldn't find any possible way to get the URL of "Discussion" or "CheckSuite", so we are not displaying them as a link.

#### Screenshots
Earlier:
![image](https://github.com/Brightscout/mattermost-plugin-github/assets/55234496/f3f48a45-d254-48a3-be73-a0f5bb9e5a13)

Now:
![image](https://github.com/Brightscout/mattermost-plugin-github/assets/55234496/1a88bdd9-259e-45d7-a643-6c7f60a4c4c8)

#### Possible risk:
- If for some specific/unknown type of notification, the repo link is not present it might not be displayed properly.

#### What to test:
- Links in the response of the `/github todo` command are rendered and working properly.

###### Steps to reproduce
1. Connect your Github account to MM.
2. Create notifications of different types on Github, Like Discussion, checkSuite, PullRequest, etc.
3. Run the `/github todo` command in any MM channel.

###### Environment:
Plugin version: v2.1.6
MM version: v7.8.2

#### Ticket Link
Fixes #693

2023-09-26 09:00 UTC, hanzei requested changes

2023-09-26 09:00 UTC, hanzei commented on server/plugin/utils.go
> +	}
2/5 that we want consistency here. All variants of `titlePart` should either have a `:` or not.

2023-09-27 08:12 UTC, raghavaggarwal2308 commented on server/plugin/utils.go
> +func getToDoDisplayText(baseURL, title, url, notifType string, repository *github.Repository) string {
@hanzei The function `getToDoDisplayText` is being used at multiple places and we don't have the repository information there. So, we won't be able to change it.
Example:
- [Review requests](https://github.com/mattermost/mattermost-plugin-github/blob/92736d3961d2cf010ec448ca6f5b09698c002efe/server/plugin/plugin.go#L863): We do not have the repository information in the `pr` here. So, we are sending "nil" in that case.

2023-09-27 08:36 UTC, hanzei commented on server/plugin/utils.go
> +func getToDoDisplayText(baseURL, title, url, notifType string, repository *github.Repository) string {
`pr` is a `*github.Issue`, which does have a `Repository` field. Can that be used? Or is that always `nil`?

2023-09-27 08:53 UTC, raghavaggarwal2308 commented on server/plugin/utils.go
> +func getToDoDisplayText(baseURL, title, url, notifType string, repository *github.Repository) string {
@hanzei Yes, the Repository field is `nil` here. 
This is an example of the data we have:
https://go.dev/play/p/aieDOFMCE79

2023-09-27 09:48 UTC, hanzei approved these changes
LGTM :+1:

2023-09-27 14:10 UTC, mickmister approved these changes

2023-11-21 10:07 UTC, AayushChaudhary0001 approved these changes
**Tested and Approved**
All the links are reflected well and redirecting the user correctly to the desired page, LGTM.

2023-11-22 21:21 UTC, merged