Support to configure multiple Github Organizations
mattermost/mattermost-plugin-github pull request #707
Opened 2023-11-01 14:27 UTC by khareyash05

#### Summary

Configure support to multiple Github organizations 
#### Ticket Link
Fixes #552

2023-11-01 14:27 UTC, mattermost-build commented
Hello @khareyash05,

Thanks for your pull request! A Core Committer will review your pull request soon. For code contributions, you can learn more about the review process [here](https://developers.mattermost.com/contribute/getting-started/code-review/).

Per the [Mattermost Contribution Guide](https://developers.mattermost.com/contribute/getting-started/), we need to add you to the list of [approved contributors](https://docs.google.com/spreadsheets/d/1NTCeG-iL_VS9bFqtmHSfwETo5f-8MQ7oMDE5IUYJi_Y/pubhtml?gid=0&single=true) for the Mattermost project.

**Please help complete the Mattermost [contribution license agreement](http://www.mattermost.org/mattermost-contributor-agreement/)?**
Once you have signed the CLA, please comment with `/check-cla` and confirm that the CLA check is green.

This is a standard procedure for many open source projects.

Please let us know if you have any questions.

We are very happy to have you join our growing community! If you're not yet a member, please consider joining our [Contributors community channel](https://pre-release.mattermost.com/core/channels/tickets) to meet other contributors and discuss new opportunities with the core team.

2023-11-01 14:29 UTC, khareyash05 commented
/check-cla

2023-11-01 14:32 UTC, khareyash05 commented
hi @hanzei . I am actually facing a problem in [https://github.com/mattermost/mattermost-plugin-github/blob/master/server/plugin/plugin.go#L166](https://github.com/mattermost/mattermost-plugin-github/blob/master/server/plugin/plugin.go#L166) . It expect a single organization name for creating a new Client for graphql. How can this be tackled for multiple orgs?

2023-11-06 11:49 UTC, hanzei commented
Does it make sense to move the org name out of the graphql client and pass the list of orgs as part of  `GetLHSData`?

2023-11-07 15:15 UTC, khareyash05 commented
Will try and let you know! That might help Thanks

2023-11-09 14:17 UTC, khareyash05 commented
> Does it make sense to move the org name out of the graphql client and pass the list of orgs as part of `GetLHSData`?

@hanzei If i understood it correctly, graphql.NewClient expects an organization. How can we tackle that issue? Passing organizations through `GetLHSData` will work for utility function `getLHSData` but how will be tackle the NewClient function? Can we consider passing orgs as concatenated string? Through my limited understanding of Go, this was I could think of. Kindly help

2023-11-20 01:02 UTC, mattermost-build commented
This PR has been automatically labelled "stale" because it hasn't had recent activity.
A core team member will check in on the status of the PR to help with questions.
Thank you for your contribution!

2023-12-18 15:25 UTC, hanzei commented
Sorry for the delay.

If we are passing the org as part of `GetLHSData`, we can remove `org` from `graphql.Client`. It's no longer needed.

2023-12-19 09:24 UTC, hanzei requested changes
Thanks for the PR @khareyash05 :+1: 

I left my comments down below. To summarize, I'm not 100% sure that the changes work. Did you test them?

2023-12-19 09:24 UTC, hanzei commented on server/plugin/configuration.go
> +	GitHubOrgs                  []string `json:"githuborgs"`
How does this change affect existing installation? E.g., does the previous value from `githuborg` get carried over to `githuborgs`?

2023-12-19 09:24 UTC, hanzei commented on server/plugin/plugin.go
> +	// an issue here to check of graphql client
What does that mean?

2023-12-19 09:24 UTC, hanzei commented on server/plugin/plugin.go
> +		configOrg := strings.TrimSpace(org)
Isn't trimming the spaces already done as part of `sanitize()`?

2023-12-19 09:24 UTC, hanzei commented on server/plugin/plugin.go
> +		}
Can this case happen?

2023-12-19 09:24 UTC, hanzei commented on server/plugin/plugin.go
> +		isMember = isMember || true
That seems off.

2023-12-19 09:24 UTC, hanzei commented on server/plugin/plugin.go
> +	}
Is it enough to check for `len(config.GitHubOrgs) > 0`?

2023-12-19 09:24 UTC, hanzei commented on server/plugin/telemetry.go
> +		"is_organization_locked":        config.GitHubOrgs,
The values of `is_organization_locked` is still a `bool`. Should we use `p.isOrganizationLocked()` instead?

2023-12-19 09:24 UTC, hanzei commented on server/plugin/utils.go
> +	if len(orgs) != 0 {
```suggestion
	if len(orgs) > 0 {
```

2023-12-19 09:24 UTC, hanzei commented on server/plugin/command.go
> +		subscriptionsAdd.AddNamedStaticListArgument("exclude-org-member-"+org, "Events triggered by organization members of "+org+" will not be delivered (the organization config should be set, otherwise t
Let's keep that flag as it is for now. The gist of the flag stays the same even with multiple orgs: It limits the subscription to all configured orgs.

2023-12-19 09:24 UTC, hanzei commented on server/plugin/api.go
> +		Organizations       []string               `json:"organization"`
Does the webapp need to get updated because of this change?

2023-12-19 09:24 UTC, hanzei commented on server/plugin/api.go
> +		if org == "" {
Can this case happen?

2024-04-26 19:45 UTC, mickmister commented
Hi @khareyash05, checking in to see how you're doing. Do you have any questions about this task?

Thanks @khareyash05!!

2024-04-27 10:11 UTC, khareyash05 commented
> Hi @khareyash05, checking in to see how you're doing. Do you have any questions about this task?
> 
> Thanks @khareyash05!!

Hey @mickmister Not able to understand the work to do. Closing the PR. Thanks.

2024-04-27 10:11 UTC, closed without merging