Typescript migration of client/actions and some components
mattermost/mattermost-plugin-github pull request #785
Opened 2024-06-03 06:18 UTC by mickmister

#### Summary

#### Ticket Link

2024-07-10 11:54 UTC, raghavaggarwal2308 requested changes

2024-07-10 11:54 UTC, raghavaggarwal2308 commented on webapp/src/components/github_label_selector/index.ts
> +}) as unknown as Actions;
Is this correct to use `unknown` here?

2024-07-10 11:54 UTC, raghavaggarwal2308 commented on webapp/src/components/issue_attribute_selector.tsx
> +                    onChange={this.onChange as any}
Is it possible to add a proper type here and on line 134 ?

2024-10-10 01:02 UTC, mattermost-build commented
This PR has been automatically labelled "stale" because it hasn't had recent activity.
A core team member will check in on the status of the PR to help with questions.
Thank you for your contribution!

2024-10-28 15:05 UTC, wiggin77 commented
@raghavaggarwal2308 this is a large PR that is out of date.  I think we should close it and replace with smaller PRs that convert fewer components at a time.   Thoughts?

2024-11-12 07:51 UTC, raghavaggarwal2308 commented
@wiggin77 Sounds good, closing it for now, will create smaller PRs.

2024-11-12 07:51 UTC, closed without merging