added testcase for some functions in server/api.go
mattermost/mattermost-plugin-github pull request #844
Opened 2024-11-04 09:37 UTC by Kshitij-Katiyar

#### Summary
Added unit test cases for the following functions in server/api.go file
- GetToken
- GetGitHubUser
- ParseRepo

2024-11-04 16:03 UTC, wiggin77 commented on server/plugin/api_test.go
> -		"not authorized": {
Shouldn't we have a `not authorized`test?

2024-11-08 22:08 UTC, wiggin77 approved these changes
LGTM :+1:

2024-12-27 08:55 UTC, raghavaggarwal2308 requested changes
@Kshitij-Katiyar There are a lot of unrelated changes in this PR, can you please check?

2025-01-22 05:38 UTC, Kshitij-Katiyar commented
@raghavaggarwal2308 I have resolved the conflicts, please review

2025-03-06 10:03 UTC, raghavaggarwal2308 approved these changes

2025-03-06 10:03 UTC, merged

2025-03-12 07:48 UTC, hanzei commented
@raghavaggarwal2308 The PR broke `master`, see https://github.com/mattermost/mattermost-plugin-github/actions/runs/13696089769/job/38298725258. Can you please fix that?

2025-03-12 08:34 UTC, Kshitij-Katiyar commented
> @raghavaggarwal2308 The PR broke `master`, see https://github.com/mattermost/mattermost-plugin-github/actions/runs/13696089769/job/38298725258. Can you please fix that?

@hanzei Created a PR for the same