Added testcase for more functions in api/command.go
mattermost/mattermost-plugin-github pull request #846
Opened 2024-11-05 12:20 UTC by Kshitij-Katiyar

#### Summary
Added testcase for the following api/command.go functions:
- HandleMuteCommand(
- ArrayDifference
- GetSubscribedFeatures
- HandleSubscriptionsList

2024-12-10 03:04 UTC, wiggin77 approved these changes

2024-12-19 10:19 UTC, raghavaggarwal2308 requested changes

2024-12-19 10:19 UTC, raghavaggarwal2308 commented on server/plugin/command_test.go
> +	mockKvStore, mockAPI, _, _, _ := GetTestSetup(t)
mockAPI is never used

2024-12-19 10:19 UTC, raghavaggarwal2308 commented on server/plugin/command_test.go
> +		b        []string
```suggestion
		arr1        []string
		arr2       []string
```

2024-12-19 10:19 UTC, raghavaggarwal2308 commented on server/plugin/command_test.go
> +						Repositories: map[string][]*Subscription{
create a util for this, a similar thing is used below as well

2025-03-10 12:21 UTC, Kshitij-Katiyar commented on server/plugin/command_test.go
> +	mockKvStore, mockAPI, _, _, _ := GetTestSetup(t)
used in the immediate next line

2025-03-10 15:29 UTC, Kshitij-Katiyar commented on server/plugin/command_test.go
> +						Repositories: map[string][]*Subscription{
these values are too nested and compilcated. Making a util will be difficult for them

2025-03-24 05:58 UTC, raghavaggarwal2308 approved these changes

2025-03-24 05:58 UTC, merged