[MM-918]: Added testcase for more functions in command.go
mattermost/mattermost-plugin-github pull request #847
Opened 2024-11-12 08:15 UTC by Kshitij-Katiyar

#### Summary
Added server test cases in command.go for the below function:
- CreatePost
- HandleUnsubscribe
- HandleSettings
- HandleIssue
- IsAuthorizedSysAdmin
- SliceContainsString

2024-12-19 10:22 UTC, raghavaggarwal2308 requested changes

2024-12-19 10:22 UTC, raghavaggarwal2308 commented on server/plugin/command_test.go
> +						Repositories: map[string][]*Subscription{
Create util if possible as mentioned in previous PR https://github.com/mattermost/mattermost-plugin-github/pull/846#discussion_r1891561185

2024-12-19 10:22 UTC, raghavaggarwal2308 commented on server/plugin/command_test.go
> +			tc.setup()
Add mockAPI.expectedCall=nil in all the testcases

2025-03-10 11:06 UTC, Kshitij-Katiyar commented on server/plugin/command_test.go
> +						Repositories: map[string][]*Subscription{
Very much customized for each event, util wont work

2025-04-09 10:36 UTC, raghavaggarwal2308 approved these changes

2025-04-09 11:44 UTC, merged