[MM-956]: Added server testcase for webhook.go
mattermost/mattermost-plugin-github pull request #855
Opened 2024-11-25 08:01 UTC by Kshitij-Katiyar

#### Summary
Added server testcase for webhook.go

2024-12-10 02:14 UTC, wiggin77 approved these changes

2024-12-10 07:57 UTC, raghavaggarwal2308 requested changes

2024-12-10 07:57 UTC, raghavaggarwal2308 commented on server/plugin/webhook_test.go
> +	mockKvStore, mockAPI, _, _, _ := GetTestSetup(t)
move inside, as it can cause some issues later

2024-12-10 07:57 UTC, raghavaggarwal2308 commented on server/plugin/webhook_test.go
> +	mockKvStore, mockAPI, _, _, _ := GetTestSetup(t)
```suggestion
	mockKVStore, mockAPI, _, _, _ := GetTestSetup(t)
```

2024-12-10 07:57 UTC, raghavaggarwal2308 commented on server/plugin/webhook_test.go
> +					if v, ok := value.(**Subscriptions); ok {
Why are we using double * here?

2024-12-10 07:57 UTC, raghavaggarwal2308 commented on server/plugin/webhook_test.go
> +				mockKvStore.EXPECT().Get(SubscriptionsKey, gomock.Any()).DoAndReturn(func(key string, value interface{}) error {
Create separate functions for the nested one. Its getting very complicated here

2024-12-10 07:57 UTC, raghavaggarwal2308 commented on server/plugin/webhook_test.go
> +			name:        "no subscription found",
```suggestion
			name:        "No subscription found",
```
For consistency, check everywhere

2025-01-28 10:25 UTC, Kshitij-Katiyar commented on server/plugin/webhook_test.go
> +					if v, ok := value.(**Subscriptions); ok {
Because pointer of pointer is used here
![Screenshot from 2025-01-28 15-54-37](https://github.com/user-attachments/assets/3136e571-87e8-47da-bba0-2e098835f26a)

2025-01-28 11:19 UTC, Kshitij-Katiyar commented
@raghavaggarwal2308 FIxed the comments, please re-review

2025-02-03 11:24 UTC, raghavaggarwal2308 commented on server/plugin/webhook_test.go
> +					if v, ok := value.(**Subscriptions); ok {
@Kshitij-Katiyar I do not think we need the double pointer here.

2025-03-24 06:02 UTC, raghavaggarwal2308 approved these changes

2025-04-07 10:40 UTC, Kshitij-Katiyar commented on server/plugin/webhook_test.go
> +					if v, ok := value.(**Subscriptions); ok {
@raghavaggarwal2308 Double-pointers are very much required here to handle the case of `no subscription stored`
Using single pointer can make the code more complicated but we can do it.
Let me know your thoughts on this

2025-05-30 10:31 UTC, merged