[MM-974]: Added testcase fore more functions in webhook.go
mattermost/mattermost-plugin-github pull request #857
Opened 2024-11-28 09:13 UTC by Kshitij-Katiyar

#### Summary
Added testcase for more functions in webhook.go

#### Original PR
https://github.com/mattermost/mattermost-plugin-github/pull/855

2024-12-02 17:23 UTC, wiggin77 approved these changes
LGTM :+1:

2024-12-22 13:12 UTC, raghavaggarwal2308 requested changes

2024-12-22 13:12 UTC, raghavaggarwal2308 commented on server/plugin/webhook_test.go
> +
Add mockAPI.ExpectedCalls = nil

2024-12-22 13:12 UTC, raghavaggarwal2308 commented on server/plugin/webhook_test.go
> +				mockKvStore.EXPECT().Get("reviewerUser_githubusername", gomock.Any()).DoAndReturn(func(key string, value interface{}) error {
Create util for return value/func

2024-12-22 13:12 UTC, raghavaggarwal2308 commented on server/plugin/webhook_test.go
> +				mockKvStore.EXPECT().Get("subscriptions", gomock.Any()).Return(nil).Times(1)
Replace gomock.an() whereever possible

2024-12-22 13:12 UTC, raghavaggarwal2308 commented on server/plugin/webhook_test.go
> +				mockKvStore.EXPECT().Get("subscriptions", gomock.Any()).Return(nil).Times(1)
we can use anythingOfType instead

2024-12-22 13:12 UTC, raghavaggarwal2308 commented on server/plugin/webhook_test.go
> +						*v = &Subscriptions{
Util for this

2025-04-09 10:38 UTC, raghavaggarwal2308 approved these changes

2025-04-16 10:56 UTC, merged